[hyperparameters]
p_val = 2
margin = 0.5
batch_size = 32
embedding_size = 128
triplet_swapping = true

[training]
seed = 4242
pre_trained = false
epochs = 15_000
print_iter = 50
val_iter = 600
name = "0.5_margin"

[training.shoemark_augmentation]
max_translation = [64, 32]
max_rotation = 45
max_scale = 0.25
flip = true
    
[training.shoeprint_augmentation]
max_translation = [32, 16]
max_rotation = 22
max_scale = 0.125
flip = false

[data]
shoeprint_data_dir = "/home/struan/Vault/University/Doctorate/Data/Siamese/Shoeprints"
shoeprint_dataset_mean = [0.8864, 0.8864, 0.8864]
shoeprint_dataset_std = [0.2424, 0.2424, 0.2424]

shoemark_data_dir = "/home/struan/Vault/University/Doctorate/Data/Siamese/Shoemarks"
shoemark_dataset_mean = [0.6739, 0.6194, 0.5622]
shoemark_dataset_std = [0.2489, 0.2591, 0.2871]

wvu_data_dir = "/home/struan/Vault/University/Doctorate/Data/Siamese/Testing/WVU2019/"
fid_data_dir = "/home/struan/Vault/University/Doctorate/Data/Siamese/Testing/FID-300/Shoeprints/"

image_size = [512, 256]

